/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import static java.sql.DriverManager.println;
import javax.swing.JFrame;
import modelo.AdminBD;
import modelo.Candidato;
import modelo.Grupo;

/**
 *
 * @author Jhon Nash
 */
public class JFrameFormCandidato extends JFrame {
    Candidato candidato;
    Grupo grupo;
    AdminBD adminBD;
    static int i;
    /**
     * Creates new form jFrameFormCandidato
     */
    public JFrameFormCandidato() {
        initComponents();
        actualizaComboBox();
        inicializaRdBtn();
     
    }
    
    public void inicializaRdBtn(){
       this.jtxtLugar.setEditable(false);
       this.jComBoxHora.setEnabled(false);
        
        
    }
    
    public void actualizaComboBox(){
       this.jComBoxCarrera.addItem("Ing. de Software");
       this.jComBoxCarrera.addItem("Lic. Arte y Patrimonio Cultural");
       this.jComBoxCarrera.addItem("Lic. Ciencias Politicas");
       this.jComBoxCarrera.addItem("Lic. Ciencias Sociales");
       this.jComBoxCarrera.addItem("Lic. Comunicacion y cultura");
       this.jComBoxCarrera.addItem("Lic. Creacion Literaria");
       this.jComBoxCarrera.addItem("Lic. Filosofia");
       this.jComBoxCarrera.addItem("Lic. Historia");
       this.jComBoxCarrera.addItem("Lic. Derecho");
       
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jlabNombre = new javax.swing.JLabel();
        jLabApPaterno = new javax.swing.JLabel();
        jLabApMaterno = new javax.swing.JLabel();
        jLabMatricula = new javax.swing.JLabel();
        jLabCarrera = new javax.swing.JLabel();
        jLabGeneracion = new javax.swing.JLabel();
        jLabCorrElectronico = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtPaterno = new javax.swing.JTextField();
        jtxtApellidoMaterno = new javax.swing.JTextField();
        jtxtMatricula = new javax.swing.JTextField();
        jComBoxCarrera = new javax.swing.JComboBox<>();
        jtxtGeneracion = new javax.swing.JTextField();
        jtxtCorrElectronico = new javax.swing.JTextField();
        jLabTelCelular = new javax.swing.JLabel();
        jLabNomTesis = new javax.swing.JLabel();
        jLabDircTesis = new javax.swing.JLabel();
        jtxtTelCelular = new javax.swing.JTextField();
        jtxtNomTesis = new javax.swing.JTextField();
        jtxtDircTesis = new javax.swing.JTextField();
        jLabTrabajo = new javax.swing.JLabel();
        jRadBtSi = new javax.swing.JRadioButton();
        jRadBtnNo = new javax.swing.JRadioButton();
        jtxtLugar = new javax.swing.JTextField();
        jLabLugar = new javax.swing.JLabel();
        jLabHora = new javax.swing.JLabel();
        jComBoxHora = new javax.swing.JComboBox<>();
        jLabFoto = new javax.swing.JLabel();
        jbtnAgregarFoto = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SISTEMA DE APOYO A LA TITULACION");

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        jlabNombre.setText("Nombre de Candidato");

        jLabApPaterno.setText("Apellido Paterno");

        jLabApMaterno.setText("Apellido Materno");

        jLabMatricula.setText("Matricula");

        jLabCarrera.setText("Carrera");

        jLabGeneracion.setText("Generacion");

        jLabCorrElectronico.setText("Correo Electronico");

        jtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreActionPerformed(evt);
            }
        });

        jComBoxCarrera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComBoxCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComBoxCarreraActionPerformed(evt);
            }
        });

        jLabTelCelular.setText("Telefono Celular");

        jLabNomTesis.setText("Nombre de Tasis");

        jLabDircTesis.setText("Director de Tesis");

        jLabTrabajo.setText("Trabajas");

        jRadBtSi.setText("Si");
        jRadBtSi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadBtSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBtSiActionPerformed(evt);
            }
        });

        jRadBtnNo.setText("No");
        jRadBtnNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadBtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBtnNoActionPerformed(evt);
            }
        });

        jLabLugar.setText("Lugar");

        jLabHora.setText("Hora");

        jComBoxHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8 hrs x 16 hrs", "12 hrs x 12 hrs", "24 hrs x 24 hrs", "24 hrs x 48 hrs", "fines de semana", "medio tiempo", "otro..." }));
        jComBoxHora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabFoto.setBackground(new java.awt.Color(255, 255, 255));
        jLabFoto.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));

        jbtnAgregarFoto.setText("Agregar foto");
        jbtnAgregarFoto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images.jpg"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Anexar Cartas"), "Anexar Cartas"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtPaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtApellidoMaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlabNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabCarrera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabMatricula)
                                            .addGap(65, 65, 65))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabDircTesis)
                                                .addComponent(jLabNomTesis)
                                                .addComponent(jLabTrabajo)
                                                .addComponent(jLabLugar)
                                                .addComponent(jLabHora))
                                            .addGap(23, 23, 23)))
                                    .addComponent(jLabGeneracion)
                                    .addComponent(jLabCorrElectronico)
                                    .addComponent(jLabTelCelular)
                                    .addComponent(jLabApMaterno)
                                    .addComponent(jLabApPaterno))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtxtCorrElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtNomTesis, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtDircTesis, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jRadBtSi)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jRadBtnNo)))
                                    .addComponent(jComBoxHora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGuardar)
                        .addGap(107, 107, 107))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnAgregarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlabNombre)
                                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabApPaterno)
                                    .addComponent(jtxtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(jLabApMaterno)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabMatricula, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabCarrera))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnAgregarFoto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabGeneracion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabCorrElectronico)
                    .addComponent(jtxtCorrElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabTelCelular)
                            .addComponent(jtxtTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabNomTesis)
                            .addComponent(jtxtNomTesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabDircTesis)
                            .addComponent(jtxtDircTesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabTrabajo)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadBtSi)
                                .addComponent(jRadBtnNo))))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabLugar)
                    .addComponent(jtxtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabHora)
                    .addComponent(jComBoxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGuardar)
                    .addComponent(jBtnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComBoxCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComBoxCarreraActionPerformed
 
    }//GEN-LAST:event_jComBoxCarreraActionPerformed

    private void jRadBtSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBtSiActionPerformed
        this.jtxtLugar.setEditable(true);
        this.jComBoxHora.setEnabled(true);
        this.jRadBtnNo.setSelected(false);
        
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jRadBtSiActionPerformed

    private void jRadBtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBtnNoActionPerformed
        // TODO add your handling code here:
       this.jtxtLugar.setEditable(false);
       this.jComBoxHora.setEnabled(false);
       this.jRadBtSi.setSelected(false);
       
       
       
    }//GEN-LAST:event_jRadBtnNoActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        // TODO add your handling code here:
        candidato = new Candidato();
        grupo = new Grupo();
        adminBD = new AdminBD();
        
        grupo.agregaAceptado(this.jtxtMatricula.getText(), this.jtxtNombre.getText(), this.jtxtPaterno.getText(), this.jtxtApellidoMaterno.getText(), this.jtxtCorrElectronico.getText(), this.jtxtGeneracion.getText(), Integer.parseInt(this.jtxtTelCelular.getText()), Integer.parseInt(this.jtxtTelCelular.getText()));
        candidato= grupo.getCandidato();
        adminBD.insertarCandidato(candidato);
        this.i++;
        this.dispose();
        
        
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreActionPerformed

    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComBoxCarrera;
    private javax.swing.JComboBox<String> jComBoxHora;
    private javax.swing.JLabel jLabApMaterno;
    private javax.swing.JLabel jLabApPaterno;
    private javax.swing.JLabel jLabCarrera;
    private javax.swing.JLabel jLabCorrElectronico;
    private javax.swing.JLabel jLabDircTesis;
    private javax.swing.JLabel jLabFoto;
    private javax.swing.JLabel jLabGeneracion;
    private javax.swing.JLabel jLabHora;
    private javax.swing.JLabel jLabLugar;
    private javax.swing.JLabel jLabMatricula;
    private javax.swing.JLabel jLabNomTesis;
    private javax.swing.JLabel jLabTelCelular;
    private javax.swing.JLabel jLabTrabajo;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadBtSi;
    private javax.swing.JRadioButton jRadBtnNo;
    private javax.swing.JButton jbtnAgregarFoto;
    private javax.swing.JLabel jlabNombre;
    private javax.swing.JTextField jtxtApellidoMaterno;
    private javax.swing.JTextField jtxtCorrElectronico;
    private javax.swing.JTextField jtxtDircTesis;
    private javax.swing.JTextField jtxtGeneracion;
    private javax.swing.JTextField jtxtLugar;
    private javax.swing.JTextField jtxtMatricula;
    private javax.swing.JTextField jtxtNomTesis;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtPaterno;
    private javax.swing.JTextField jtxtTelCelular;
    // End of variables declaration//GEN-END:variables
}
